name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group afu-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 0a933423-372a-475a-8082-86039eaf1d0f
          region: West Europe
          template: ./arm-template/resourcegroup.json
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: afu-githubactions
          subscriptionId: 0a933423-372a-475a-8082-86039eaf1d0f
          region: West Europe
          template: ./arm-template/storageaccount.json
          parameters: ./arm-template/storageaccount.parameters.json
          deploymentMode: incremental
